[package]
name = "apex_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
process-memory = "0.5.0"
sysinfo = "0.28.2"
pelite = "0.10.0"
skidscan = "2.0.1"